# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('programme', models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE')], default='CSE', max_length=3)),
                ('batch', models.CharField(max_length=4)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('current_CGPA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('roomno', models.IntegerField()),
                ('hostel', models.CharField(max_length=40)),
                ('pa_flatno', models.CharField(max_length=50)),
                ('pa_line1', models.CharField(max_length=150)),
                ('pa_line2', models.CharField(max_length=150)),
                ('pa_city', models.CharField(max_length=50)),
                ('pa_state', models.CharField(max_length=50)),
                ('pa_country', models.CharField(max_length=50)),
                ('pa_pincode', models.IntegerField()),
                ('private', models.BooleanField(default=False)),
                ('tutorial_section', models.CharField(max_length=2)),
                ('probation', models.BooleanField(default=False)),
            ],
        ),
    ]
