# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20170328_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
